document.title="洽客-任务详情"; 
$.createSecondMenu("home","我的任务");

var task = ["",
	{
		id:1,
		name:"公众号绑定授权",
		content:"完成公众号和洽客的绑定授权，充分使用洽客各项功能",
		video:"https://qncdn.qiakr.com/movie/公众号绑定授权",
		imgText:'<div class="original-content"><p><img src="https://qiakr.kf5.com/attachments/download/114080/001557511a431ae43a622090bcd0002/" title="" alt="blob.png"></p><p><br></p><p>进入洽客后台，首页如图通知栏绑定微信公众号的提示<br></p><p>点击“授权绑定公众号”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108219/001556e9591b83f7f7f0bf5abcfadb1/" title="" alt="blob.png"><br></p><p><br></p><p><strong>微信公众号要求：</strong></p><p>必须是微信服务号</p><p>必须已通过微信认证</p><p><br></p><p>点击“微信公众号登陆授权”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108221/001556e95deed8d96213494347618f9/" title="" alt="blob.png"></p><p><br></p><p>此时您已进入微信公众平台的官方授权页面。</p><p>输入公众号账号密码，“登陆并授权”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108225/001556e9614c3aef34a3a323b317f1f/" title="" alt="blob.png"></p><p><br></p><p>此时会出现公众号二维码安全验证信息，需要公众号管理员使用微信扫描确认。</p><p>即可完成公众号与洽客的授权对接</p><p><br></p><p style="text-align:left;"><img src="https://qiakr.kf5.com/attachments/download/108236/001556e96fd1d71f8dc71785f587ef0/" title="" alt="blob.png"></p><p style="text-align:left;"><br></p><p style="text-align:left;">一个洽客账号只可以绑定一个微信公众号，绑定后为了您现有账户的会员数据一致性，不支持直接更换其他公众号。<br><br></p><p style="text-align:left;"><br></p><p style="text-align:left;"><a href="http://www.qiakr.com/admin/bindingWechat.htm" target="blank"><img src="https://qiakr.kf5.com/attachments/download/171372/00155b5c898e5c6c5b769a2106a5442/" title="" alt="blob.png"></a></p><p style="text-align:left;"><br></p><p><br></p></div>'
	},
	{
		id:2,
		name:"微信自定义菜单管理",
		content:"自定义您的微信菜单，添加您想要的内容或入口",
		video:"https://qncdn.qiakr.com/movie/微信自定义菜单管理",
		imgText:'<div class="original-content"><p><img src="https://qiakr.kf5.com/attachments/download/108269/001556e98d8392440362a4304fff75b/" title="" alt="blob.png"></p><p>点击右上角的设置，进入“微信自定义菜单管理”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108266/001556e987d875e0050f9a123dc4171/" title="" alt="blob.png"></p><p><br></p><p>第一次设置自定义菜单，建议点击“使用初始设置”</p><p>洽客已经为您预置了常用的功能菜单，点击预置后您可以根据自身需求修改</p><p><br></p><p>点击右侧“添加菜单”可以新增微信主菜单，最大支持3个</p><p>点击右侧“添加子菜单”可以在当前主菜单新增子菜单，最大支持5个</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108277/001556e98faa1f2d64c21a2d3debead/" title="" alt="blob.png"></p><p><img src="https://qiakr.kf5.com/attachments/download/108278/001556e990ba5754451795c7c198a11/" title="" alt="blob.png"></p><p><br></p><p>菜单类型：目前支持直接跳转链接，您可以点击“菜单类型”选择需要跳转的洽客功能，也可以选择自定义网页链接</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108280/001556e9925d6a0865adf13828732c0/" title="" alt="blob.png"></p><p><br></p><p>最后点击“保存菜单并发布”即可发布自定义菜单</p><p>由于微信客户端缓存，需要24小时内微信客户端才会展现出修改后的菜单。可以尝试取消关注公众账号后再次关注，则可以看到创建后的效果。（新关注用户不会有影响）</p><p><br></p><p><br></p><p style="text-align:left;"><a href="http://www.qiakr.com/admin/settings.htm#menu" target="blank"><img src="https://qiakr.kf5.com/attachments/download/171378/00155b5c90adaf9b7f81122b7a9f173/" title="" alt="blob.png"></a></p><p><br></p></div>'
	},
	{
		id:3,
		name:"微信首访语设置",
		content:"引导新关注的粉丝使用服务号，留下美好第一印象",
		video:"https://qncdn.qiakr.com/movie/微信首访语设置",
		imgText:'<div class="original-content"><p>点击右上角设置，进入“微信首访语设置”，在输入框内输入内容并保存即可。</p><p><br></p><p>微信首访语：消费者首次关注微信公众号时，自动回复的文字内容。若消费者是扫描的导购二维码关注，同时也会回复绑定导购的提示信息。<br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/266038/0015618b169e092ddaa9558e95bf78e/" title="" alt="blob.png"></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/266049/0015618b2b022da27863aba9c142eb3/" title="" alt="blob.png"></p><p><br></p><p><br></p></div>'
	},
	{
		id:4,
		name:"公司认证和财务审核",
		content:"完成该任务后方能结算回款",
		video:"https://qncdn.qiakr.com/movie/公司认证和财务审核",
		imgText:'<div class="original-content"><p>通过微信支付、支付宝等在线支付方式产生的订单，我们会在每周两次与您进行结款，需要您提供相关银行账户。<br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/171451/00155b5d0c5ec6da8674bb852ea2085/" title="" alt="blob.png"></p><p><br></p><p>进入洽客后台，点击“填写财务结算信息”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108736/001556ebc90753bac328fd23f0e76d2/" title="" alt="blob.png"></p><p><br></p><p>根据页面要求填写信息并提交即可，审核人员会在3个工作日内审核完毕</p><p><br></p></div>'
	},
	{
		id:5,
		name:"新建门店",
		content:"将您的门店搬到线上微商城中",
		video:"https://qncdn.qiakr.com/movie/新建门店",
		imgText:'<div class="original-content"><p><img src="https://qiakr.kf5.com/attachments/download/108290/001556e99eab05988c298d88e6059ab/" title="" alt="blob.png"></p><p><br></p><p>进入洽客门店板块，点击“新建门店”</p><p><img src="https://qiakr.kf5.com/attachments/download/108331/001556e9d512470742e03e8fe95b173/" title="" alt="blob.png"></p><p><br></p><p>根据表单填写门店基础资料</p><p>门店名称：您的实际门店名称</p><p>联系地址：方便用户找到您的门店</p><p>联系电话：方便用户电话沟通</p><p>选择品牌：门店主要售卖的品牌</p><p>门店Logo：用于在微商城显示</p><p>门店店招：用于在微商城显示</p><p>营业时间</p><p>简单介绍</p><p>地理位置：已经根据您输入的门店位置锁定到对应地图坐标，您也可以手动拖动坐标到更精确的位置</p><p><br></p><p>最后点击保存即可</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/172086/00155b63612c5dd3409179fece0c5cd/" title="" alt="blob.png"></p><p><br></p><p>输入该门店导购的姓名、手机号、职位，点击“确认添加”即可完成一个导购的添加。</p><p><br></p><p>添加完导购后，导购将收到一条短信，短信内含其登陆洽客导购端的登陆密码，可以引导其安装并登陆<br><br></p><p>导购版下载链接：</p><p><a href="http://www.qiakr.com/ipa/eke.html" target="blank">http://www.qiakr.com/ipa/eke.html</a></p><p><br></p><p>二维码扫描：</p><p><img src="https://qiakr.kf5.com/attachments/download/108764/001556ebd9f26c55a02e0d948a7e594/" title="" alt="blob.png" style="margin:2px;padding:0px;border:0px;font-weight:inherit;font-style:inherit;font-size:0px;font-family:inherit;vertical-align:baseline;height:auto; width:200px;"></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108350/001556e9e47a6499f0b4e5aea3fdb02/" title="" alt="blob.png"></p><p><br></p><p>之后您也可以在门店列表，点击门店列表的“编辑”按钮，继续为该门店添加导购</p><p><br></p><p><br></p><p style="text-align:left;"><a href="http://www.qiakr.com/admin/storeList.htm" target="blank"><img src="https://qiakr.kf5.com/attachments/download/171397/00155b5ca742c5432b9124671257580/" title="" alt="blob.png"></a></p></div>'
	},
	{
		id:6,
		name:"添加导购账号",
		content:"在您的线上门店中添加对应导购，为客户提供更多服务",
		video:"https://qncdn.qiakr.com/movie/添加导购账号",
		imgText:'<div class="original-content"><p><strong>方法1： 导购管理板块添加导购</strong><br>进入“门店”，点击左侧列表的“导购管理”<br>点击右侧的“新建导购”<br><img src="https://qiakr.kf5.com/attachments/download/172034/00155b62c5d48e30e7d58d67c4f7cd7/" title="" alt="blob.png"></p><p style="text-align:left;"><br>选择需要添加的门店、导购职位、姓名、手机号信息，点击“添加导购”即可完成添加。<br><br><img src="https://qiakr.kf5.com/attachments/download/172035/00155b62d687ecc77ea415731accaff/" title="" alt="blob.png"><br><br><a href="http://www.qiakr.com/admin/salesList.htm" target="blank"><img src="https://qiakr.kf5.com/attachments/download/172037/00155b62dc33a923ed3fa35f4e31403/" title="" alt="blob.png"></a><br><br></p><p><strong>添加完导购后，导购将收到一条短信，短信内含其登陆洽客导购端的登陆密码，可以引导其安装并登陆。</strong></p><p><br></p><p>导购版下载链接：</p><p><a href="http://www.qiakr.com/ipa/eke.html" target="blank">http://www.qiakr.com/ipa/eke.html</a></p><p><br></p><p>二维码扫描：</p><p><img src="https://qiakr.kf5.com/attachments/download/108764/001556ebd9f26c55a02e0d948a7e594/" title="" alt="blob.png" style="margin:2px;padding:0px;border:0px;font-weight:inherit;font-style:inherit;font-size:0px;font-family:inherit;vertical-align:baseline;height:auto; width:200px;"></p><p><br></p><p><strong>方法2：门店管理内添加导购</strong></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108377/001556ea08eed3b3791ea64431a3c6f/" title="" alt="blob.png"></p><p><br></p><p>在门店列表，点击门店列表的“编辑”按钮，继续为该门店添加导购<br><br></p><p><img src="https://qiakr.kf5.com/attachments/download/172086/00155b63612c5dd3409179fece0c5cd/" title="" alt="blob.png"></p><p><br></p><p>输入该门店导购的姓名、手机号、职位，点击“确认添加”即可完成一个导购的添加。</p><p><br></p><p style="text-align:left;"><a href="http://www.qiakr.com/admin/storeList.htm" target="blank"><img src="https://qiakr.kf5.com/attachments/download/171397/00155b5ca742c5432b9124671257580/" title="" alt="blob.png"></a></p><p><br></p><p><br></p><p><br></p></div>'
	},
	{
		id:7,
		name:"下载导购端app",
		content:"下载导购端app，并使用导购账号登陆",
		video:"https://qncdn.qiakr.com/movie/下载导购端app",
		imgText:'<div class="original-content"><p style="text-align:left;"><strong><img src="https://qiakr.kf5.com/attachments/download/114660/001557556461f64a34875507141eef0/" title="" alt="blob.png"></strong></p><p><br></p><p style="text-align:left;">下载链接：</p><p style="text-align:left;"><a href="http://www.qiakr.com/ipa/eke.html" target="blank">http://www.qiakr.com/ipa/eke.html</a></p><p style="text-align:left;">二维码扫描：</p><p style="text-align:left;"><img src="https://qiakr.kf5.com/attachments/download/108764/001556ebd9f26c55a02e0d948a7e594/"  class="w200" alt="blob.png" ></p><p><br></p><p style="text-align:left;"><br></p><p style="text-align:left;"><br></p></div>'
	},
	{
		id:8,
		name:"导购权限设置",
		content:"设置收银台、是否能自建商品",
		video:"https://qncdn.qiakr.com/%E5%AF%BC%E8%B4%AD%E7%AB%AF%E6%9D%83%E9%99%90%E8%AE%BE%E7%BD%AE",
		imgText:'<div class="original-content"><p><strong>增加更多权限设置，可根据店长、店员，分别设置不同权限。常见使用场景：</strong></p><p><strong>a. 根据店内情况，控制店员是否可在洽客上使用现金支付、未付款订单改价、订单发货等权限。<br>b. 收银台可选择开单导购权限：店内不允许店员使用手机，可为店长开启该权限，使用公用设备（手机/Pad）登录洽客，在收银台开单功能内下单选择开单导购。</strong></p><p><br></p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><h3><strong>设置权限角色</strong><br></h3></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/311921/001564435de245a3d9074d368949e73/" title="" alt="blob.png" width="730" height="356" style="width:730px;height:356px;"></p><p>进入洽客管理后台首页，从界面右上角设置点击【权限设置】，再点击右侧导航栏进入【导购端软件权限】</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/311928/00156443692c226fea9b0ff2d65d64d/" title="" alt="blob.png"></p><p>根据您的实际业务和场景需要，为店长和店员（这里的店长和店员指的不是单一个人，而是角色）设置相应权限，设置完成后点击【保存设置】即可</p><p><br></p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><h3>设置账号角色</h3><p></p></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/312062/00156443ec79155e43f64d9df3e4632/" title="" alt="blob.png" width="738" height="253" style="width:738px;height:253px;"></p><p>进入商家管理后台首页，点击【门店】-【导购管理】进入导购管理列表</p><p>找到相应导购，并在该导购列表右侧点击【编辑】进入导购管理界面</p><p><br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/312068/00156443f46ec862e47294c374568f3/" title="" alt="blob.png"></p><p>为该导购选择对应的导购角色，选择角色后，该导购账号将获得在前文(设置角色权限)中相应角色的权限</p><p>完成后点击【保存】即可</p><p><br></p><p><br></p><p><br></p><p>* 什么是角色？</p><p>角色是指某个员工可以拥有的权限集合，设置角色可以方便地给员工批量授权或批量修改权限。如果角色拥有某一权限，那么该角色下的所有子账号都拥有这一权限。如果修改角色的权限，那么这个角色下的所有子账号都被修改了相同的权限。</p><p>商家也可以把角色理解为岗位，譬如你设置了一个“数据分析专员”的角色（岗位）并给其设置了“查看数据”的权限，那么在后台的子账号只要选择了“数据分析专员”这一角色（岗位），就会别赋予相应的“查看数据”权限</p><p><br></p></div>'
	},
	{
		id:9,
		name:"新建商品",
		content:"将您的商品搬到线上门店之中，让客户看到",
		video:"https://qncdn.qiakr.com/movie/新建商品",
		imgText:'<div class="original-content"><p><img src="https://qiakr.kf5.com/attachments/download/108503/001556eaa034d88135572f0bc6006ba/" title="" alt="blob.png"></p><p><br></p><p>进入洽客商品板块，点击“添加商品”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113834/0015574f7773153bd548265536f497f/" title="" alt="blob.png"></p><p><br></p><p>选择“发布单件商品”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108513/001556eaaaf7387bb62e612d8f4a197/" title="" alt="blob.png"></p><p><br></p><p>根据页面提示填入商品名称、价格、规格等基础信息，点击最下方的添加成功按钮即可添加成功。</p><p>图片信息可根据情况录入，若有则上传方便门店导购或结账人员快速锁定到商品。</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108555/001556eadb159cedba7eaee8baf5ec0/" title="" alt="blob.png"></p><p><br></p><p>商品添加成功后，若该商品需要上架到微商城，可以在下图界面编辑微商城的展示信息。丰富的商品图片描述可以提高微商城销售成单率。</p><p>若该商品仅在门店销售无需上架微商城，你可以点击“暂不处理”即可跳过。</p><p>当然如果之后需要上架到微商城，您依然可以在商品列表，找到该商品进行编辑。</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/108568/001556eaf46c16a2f472dcb1d727422/" title="" alt="blob.png"></p><p><br></p><p style="text-align:left;">点击“保存并上架微商城”后，即可选择需要上架的微商城所属门店。<br><br><a href="http://www.qiakr.com/admin/querySupplierStock.htm" target="blank"><img src="https://qiakr.kf5.com/attachments/download/171433/00155b5cf1a3e7f5b9b1714d269c904/" title="" alt="blob.png"></a></p></div>'
	},
	{
		id:10,
		name:"微商城上下架",
		content:"将刚才录入的商品上架到新建的门店微商城",
		video:"https://qncdn.qiakr.com/movie/微商城上下架",
		imgText:'<div class="original-content"><p><strong>微商城商品：</strong></p><p>总库商品除了进行日常的店内销售，也可以上架到微商城进行线上销售；每个门店都对应一个线上版的门店微商城，您需要将总库商品上架到需要的门店微商城。</p><p><br></p><p><strong>一. 微商城商品上架</strong></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/116642/001557701906f46e4dd291aec61620b/" title="" alt="blob.png"></p><p><br></p><p>商品如何上架到微商城：</p><p>1.进入洽客商品板块，点击“总库商品”</p><p>2.勾选需要上架的商品（如图）</p><p>3.点击“上架微商城”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/116646/0015577024bf242407e55856d60f210/" title="" alt="blob.png"></p><p><br></p><p>选择需上架的门店，点击确定即可完成微商城上架。</p><p><br></p><p><strong>二. 微商城商品查询管理</strong></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/116636/001557700e3815cb9ec31958b60b6e4/" title="" alt="blob.png"></p><p><br></p><p>微商城商品查询管理：</p><p>进入洽客商品板块，点击“微商城”</p><p>可以通过门店筛选、分类筛选快速找到已上架到微商城的商品</p><p><br></p><p><strong>列表含以下功能：</strong></p><p><strong>1. 下架：将该商品从微商城下架</strong></p><p><img src="https://qiakr.kf5.com/attachments/download/108713/001556ebadcc74008409cf7abf1b437/" title="" alt="blob.png"></p><p><br></p><p>下架：点击“下架”按钮，会提示该商品从哪些门店下架，操作选择即可</p><p><br></p><p><strong>2. 获取链接：获取该商品的微商城链接</strong></p><p><img src="https://qiakr.kf5.com/attachments/download/108722/001556ebb19364937d9f88bef701b7a/" title="" alt="blob.png"></p><p><br></p><p>点击获取链接后即可复制链接，该链接为该商品的微商城公用链接。</p><p><br></p><blockquote><p>Q：为什么是公用链接：</p><p>A：因为每个门店都有一个微商城，可根据门店类型上架不同商品，同一款商品在每个微商城的链接都是不同的，公用链接可根据当前会员绑定的门店导购，跳转到对应的门店微商城商品上。</p><p><br></p><p>Q：会员进入链接后的情况：</p><p>A：若会员已绑定过导购，则该商品默认显示为该导购所属门店商品，该商品的业绩归绑定导购所有。</p><p>若会员已绑定导购的门店，没有该商品，会轮流为该会员分配一个有该商品的门店。</p></blockquote><p><br></p><p style="text-align:left;"><a href="http://www.qiakr.com/admin/querySupplierStock.htm" target="blank"><img src="https://qiakr.kf5.com/attachments/download/171433/00155b5cf1a3e7f5b9b1714d269c904/" title="" alt="blob.png"></a></p><p style="text-align:left;"><a href="http://www.qiakr.com/admin/queryOnlineStock.htm" target="blank"><img src="https://qiakr.kf5.com/attachments/download/171441/00155b5cf8be4166512f7446287bd06/" title="" alt="blob.png"></a></p></div>'
	},
	{
		id:11,
		name:"完成开单（收银台）",
		content:"完成1笔完整成交订单（下单、付款、收货并评价）成为开单达人",
		video:"https://qncdn.qiakr.com/movie/完成开单（收银台）",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><p><span style="color:rgb(255,0,0);"><strong>收银，解决店内快速开单的场景，功能与门店版“收银台”功能基本一致</strong></span></p></li></ul><p><br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/174892/00155b90125e753c8b48f0264df3d49/" title="" alt="blob.png" width="490" height="363" style="width:490px;height:363px;"></p><p>点击主界面右下角“我的”进入我的地盘，再点击菜单中“收银”（上左图）</p><p>进入收银台，选择需要开单的商品，系统提供两种商品定位方式：列表查询和扫货查询</p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:circle;"><li><p>列表查询：</p></li></ul><p><img src="https://qiakr.kf5.com/attachments/download/175332/00155b9a1171d0dbbfed754ae72cea1/" title="" alt="blob.png" width="486" height="395" style="width:486px;height:395px;"></p><p>在商品列表中找到需要开单商品并点击，在弹出菜单中点击“加入收银台”（上左图）</p><p>选择开单商品的具体规格（尺码、颜色）和数量，确认后点击“确定”即可将商品添加到收银台（上右图）</p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:circle;"><li><p>扫货查询：</p></li></ul><p><img src="https://qiakr.kf5.com/attachments/download/175532/00155b9c9283d2e83d8229020e0161a/" title="" alt="blob.png" width="489" height="404" style="width:489px;height:404px;"></p><p>进入扫货模式后，将摄像头对准开单商品的二维码（上左图）</p><p>系统会自动读取商品条码并找到后台对应商品，确认后可以直接开单或者加入收银台</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/175604/00155b9d4b6a866a8e94ed2437344a9/" title="" alt="blob.png" width="486" height="389" style="width:486px;height:389px;"></p><p>确认订单商品：可以点击右上角“编辑”对订单进行编辑，确认后点击“开单支付”（上左图）</p><p>确认订单信息：点击“邀请会员”会弹出导购二维码，让客户使用微信扫码就能确认订单购买者信息并同时添加客户为会员；选择配送方式、支付方式后点击“确定”（上右图）</p><p><br></p><p><span style="color:rgb(255,0,0);">重要提示：如果在确认订单信息过程中跳过邀请会员，直接让客户进行支付，后台无法获取客户完整信息！</span></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/175834/00155b9ec08519ef82d49bbab590052/" title="" alt="blob.png" width="490" height="408" style="width:490px;height:408px;"></p><p>生成支付二维码：可以在二维码上方修改订单价格（需要店长权限），在界面下方根据客户需求选择支付方式，让客户使用对应客户端扫描支付二维码即可（上左图）</p><p>客户支付完成后，界面弹出订单管理信息，导购可在此界面对订单进行备注或查看客户信息</p></div>'
	},
	{
		id:12,
		name:"完成开单（微商城下单）",
		content:"微信打开您的微商城，选择一件商品下单并付款（选择门店自提）",
		video:"https://qncdn.qiakr.com/movie/完成开单（微商城下单）",
		imgText:'<div class="original-content"><blockquote><p>以下内容将从消费者角度讲述用户在线上微商城购买的完整流程</p></blockquote><p><br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/264789/001561779e5aa50f1a67a80437b7df8/" title="" alt="blob.png" width="607" height="484" style="width:607px;height:484px;"></p><p>从商户微信公众号进入店铺，按上图提示绑定相应门店和导购</p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:circle;"><li><p><span style="color:rgb(127,127,127);">如果消费者是直接从商品等其他链接进入店铺，将直接绑定对应店铺或导购，不跳出以上界面</span></p><p><span style="color:rgb(127,127,127);"></span></p></li></ul><p><br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/264900/001561784e363e473e80f78de316f0b/" title="" alt="blob.png" width="611" height="454" style="width:611px;height:454px;"></p><p>选择商品并进入商品详情页，用户在此可以查看商品的图片以及各种详细信息，也可将商品加入收藏或者购物车</p><p>点击“购买”，选择相应的规格，并确认购买数量</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/264938/001561786edab0f294d82f87062b71c/" title="" alt="blob.png" width="612" height="477" style="width:612px;height:477px;"></p><p>进入确认订单界面，用户在此可以编辑发货方式、支付方式、收货人信息、优惠券信息，确认后点击“提交订单”进入支付界面</p><p>在支付界面可以查看订单状态、订单编号等订单信息，确认后点击“立即付款”，完成付款即可</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/265072/0015617968cc1c84b2b12401cb589aa/" title="" alt="blob.png" width="610" height="471" style="width:610px;height:471px;"></p><p>支付完成后，会跳出支付成功的提示</p><p>在支付完成界面点击“完成”，进入导购评价界面，消费者可以对导购的服务作出评价</p></div>'
	},
	{
		id:13,
		name:"导购端提货码核销订单",
		content:"使用导购端app，模拟用户自提，核销刚才的微商城订单",
		video:"https://qncdn.qiakr.com/movie/导购端提货码核销订单",
		imgText:'<div class="original-content"><p><img src="https://qiakr.kf5.com/attachments/download/265090/00156179e3e92e62787a45237e5dea5/" title="" alt="blob.png" width="611" height="512" style="width:611px;height:512px;"></p><p>买家如果选择“到店自提”的发货方式，支付成功后会在订单完成界面显示提货码和提货码条码，并同时在手机上收到一条包含提货码信息的短信（请妥善保管）</p><p><br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/265851/00156188e50954210627d30a7260a95/" title="" alt="blob.png" width="817" height="452" style="width:817px;height:452px;"></p><p>顾客到店提货时，导购在导购端“我的”个人中心界面点击“提货”即可进入提货功能</p><p>导购可以直接输入顾客提供的提货码，或者通过扫一扫扫描顾客订单页的提货条码，即可完成提货</p></div>'
	},
	{
		id:14,
		name:"新会员送券",
		content:"新用户首次关注微信公众号时赠送优惠券",
		video:"https://qncdn.qiakr.com/movie/新会员送券",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><p>新会员关注微信公众号后可获得优惠券（微信公众号必须为微信认证的服务号）</p></li><li><p><a href="https://qiakr.kf5.com/posts/view/39413/" target="blank">使用场景1：关注立减 - 导购胸牌扫码</a></p></li><li><p><a href="https://qiakr.kf5.com/posts/view/39412/" target="blank">使用场景2：关注立减 - 洽客导购手机软件</a></p></li><li><p><a href="https://qiakr.kf5.com/posts/view/39411/" target="blank">使用场景3：关注立减 - 洽客门店Pad软件</a><br></p></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113366/001557400756c06a0c44acbaf84c03f/" title="" alt="blob.png"></p><p><br></p><p>进入后台活动板块，选择“新会员送券”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113377/0015574054593c45147b91086aa9ec5/" title="" alt="blob.png"></p><p><br></p><p>选择“创建新会员送券”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113387/00155740603cd326b571ec927196744/" title="" alt="blob.png"></p><p><br></p><blockquote><p>输入优惠券名称、优惠券有效期等基础信息。</p><p>优惠券名称：会在会员的优惠券信息里显示，比如“新会员送券”等</p><p>优惠券有效期：会员若领取到该优惠券，只能在这段时间里使用。</p><p>商品限制：若该券只针对特定商品才可使用，选择后选择特定商品即可。</p><p>品类限制：若该券只针对特定品类才可使用，选择后选择特定品类即可。</p><p>优惠券信息编辑无误后，点击“确定”</p></blockquote><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113388/0015574066238a88e318808f7bb52db/" title="" alt="blob.png"><br></p><p><br></p><blockquote><p>选择发放时间/活动时间，如图若此处设置了6月8日至7月3日，则此段时间内新关注微信公众号的会员才会赠送优惠券，其他时间都不会赠送。</p><p>如果是长期活动，建议将发放时间/活动时间，截止时间设置尽量长期，比如2020年</p></blockquote><p><br></p><p>点击“保存”即可创建新会员送券活动。<br></p><p><br></p><p>如果希望新会员送券送多张优惠券，可以回到列表，再次创建一个新会员送券活动，活动时间设置成一样，但优惠券设置成另外类型，即可达到一次赠送多张券的目的。</p><p><br></p><p>完成后可以点击 &nbsp;<a href="https://qiakr.kf5.com/posts/view/39413/" target="blank">使用场景1：关注立减 - 导购胸牌扫码</a>&nbsp;&nbsp;<a href="https://qiakr.kf5.com/posts/view/39412/" target="blank">使用场景2：关注立减 - 洽客导购手机软件</a>&nbsp;&nbsp;<a href="https://qiakr.kf5.com/posts/view/39411/" target="blank">使用场景3：关注立减 - 洽客门店Pad软件</a>&nbsp; 查看如何使用该功能。</p><p><br></p></div>'
	},
	{
		id:15,
		name:"买后送券活动设置",
		content:"会员下单付款后获得优惠券，吸引用户下次复购",
		video:"https://qncdn.qiakr.com/movie/买后送券活动设置",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2"><li><p>根据设定的规则，如用户购买超过100元订单，赠送优惠券用于下次消费使用，提升会员复购</p></li><li><p><a href="https://qiakr.kf5.com/posts/view/39415/" target="blank">使用场景：回店复购</a></p></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113395/00155740ce92451e8a23ca2fce6fcc1/" title="" alt="blob.png"></p><p><br></p><p>进入后台活动板块，选择“买后送券”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113397/00155740d4f8579071674189dc04fed/" title="" alt="blob.png"><br></p><p><br></p><p>选择“创建买后送券”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113398/00155740e4fca43896a2759f34da121/" title="" alt="blob.png"><br></p><p><br></p><blockquote><p>输入优惠券名称、优惠券有效期等基础信息。</p><p>优惠券名称：会在会员的优惠券信息里显示，比如“消费赠送”</p><p>优惠券有效期：会员若领取到该优惠券，只能在这段时间里使用。</p><p>商品限制：若该券只针对特定商品才可使用，选择后选择特定商品即可。</p><p>品类限制：若该券只针对特定品类才可使用，选择后选择特定品类即可。</p><p>优惠券信息编辑无误后，点击“确定”</p></blockquote><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113399/00155740edbb6be3e43b080294e688d/" title="" alt="blob.png"><br></p><p><br></p><blockquote><p>选择发放时间/活动时间，如图若此处设置了6月8日至7月3日，则此段时间内新关注微信公众号的会员才会赠送优惠券，其他时间都不会赠送。</p><p><br></p><p>发放总量：默认为不限制</p><p>场景如购物即可获得优惠券，限量500张先到先得。则此处可设置为限制500张。</p><p><br></p><p>每日限量：默认为不限制</p><p>场景如每日前10个付款订单可获得优惠券。则此处可设置为每日限制10张。</p><p><br></p><p>每人限领：默认为不限制</p><p>场景如每日前10个付款会员可获得优惠券。则此处可设置为每人限10张。</p><p><br></p><p>订单限额：默认为不限制；</p><p>场景如购物满500元获得优惠券。则此处可设置为限额500元。</p><p><br></p><p>以上场景可根据需求组合设置。</p><p><br></p><p>最后点击“保存”即可完成买后送券的活动设置。</p></blockquote><p><br></p><p>如果希望买后送券赠送多张优惠券，可以回到列表，再次创建一个买后送券活动，活动时间设置成一样，但优惠券设置成另外类型，即可达到一次赠送多张券的目的。</p><p><br></p><p>完成后可以点击&nbsp;<a href="https://qiakr.kf5.com/posts/view/39415/" target="blank">使用场景：回店复购</a>&nbsp;查看如何使用该功能。</p><p><br></p></div>'
	},
	{
		id:16,
		name:"给导购发优惠券",
		content:"发券给导购后，导购可以单独赠送优惠券到特定的会员，以提高成单",
		video:"https://qncdn.qiakr.com/movie/给导购发优惠券",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><p><a href="https://qiakr.kf5.com/posts/view/39414/" target="blank">使用场景：导购送券</a><br></p></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113327/0015573f66a18e978de71b585be8337/" title="" alt="blob.png"><br></p><p><br></p><p>进入后台活动板块，选择“发券给导购”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113329/0015573f6d1d6219c34266485da447a/" title="" alt="blob.png"></p><p><br></p><p>选择“批量发券给导购”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113330/0015573f75d4c615f13422444877650/" title="" alt="blob.png"></p><p><br></p><blockquote><p>输入优惠券名称、优惠券有效期等基础信息。</p><p>优惠券名称：会在会员的优惠券信息里显示，比如“五一特惠券”等</p><p>优惠券有效期：会员若领取到该优惠券，只能在这段时间里使用。</p><p>商品限制：若该券只针对特定商品才可使用，选择后选择特定商品即可。</p><p>品类限制：若该券只针对特定品类才可使用，选择后选择特定品类即可。</p><p>优惠券信息编辑无误后，点击“确定”</p></blockquote><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113350/0015573fdc26ea63bebc77dde2b306e/" title="" alt="blob.png"><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113354/0015573fe34a79e571be6d2fab10872/" title="" alt="blob.png"></p><p><br></p><blockquote><p>选择需要发放的导购</p><p>全部导购：给到目前所有导购</p><p>指定门店导购：可针对特定门店的导购发放优惠券；场景如某新店开张，发放促销券给到该店导购，或为了针对性提升部分门店业绩。</p><p>活动备注：可填写本次批量发放的目的，方便后期追述发放优惠券的原因。</p><p>点击“保存”即可发放成功。</p></blockquote><p><br></p><p>完成后可以点击 &nbsp;<a href="https://qiakr.kf5.com/posts/view/39414/" target="blank">使用场景：导购送券</a>&nbsp; 查看如何使用该功能。</p><p><br></p></div>'
	},
	{
		id:17,
		name:"导购二维码批量推广（高级）",
		content:"打印导购二维码，制作导购工牌",
		video:"",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2"><li><p>若店内导购规定不能使用手机，可以将导购二维码进行打印，粘贴与导购胸牌。</p></li><li><p><a href="https://qiakr.kf5.com/posts/view/39413/" target="blank">使用场景：关注立减 - 导购胸牌扫码</a></p></li></ul><p><img src="https://qiakr.kf5.com/attachments/download/113443/001557428002e6c25634ef34cde76c2/" title="" alt="blob.png"></p><p><br></p><p>此功能需已绑定微信公众号（通过微信认证的服务号），<a href="https://qiakr.kf5.com/posts/view/39290/" target="blank">点击查看如何授权绑定公众号</a></p><p><br></p><p>点击右上角的“批量下载导购二维码”，将自动下载一个二维码的压缩包文件，解压后将获取到所有导购的二维码图片，图片已经根据导购名称及手机号进行命名，您可以进行区分。</p><p><br></p><p>可以自己使用打印机打印，或携带二维码图片至打印店，打印制作导购工牌。</p></div>'
	},
	{
		id:18,
		name:"商品专题页面设置",
		content:"多种商品专题模板，如新品首发、疯狂折扣、每季精选等",
		video:"https://qncdn.qiakr.com/movie/商品专题页面设置",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2"><li><p>洽客提供多种商品展示模板，新品首发、疯狂折扣、每季精选，总有一款适合您。</p></li><li><p><a href="https://qiakr.kf5.com/posts/view/39417/" target="blank">使用场景：商品专题</a></p></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/114278/00155752e6c4f599e60c78a2d44b414/" title="" alt="blob.png"></p><p><br></p><p>进入后台活动板块，选择“商品专题”</p><p><img src="https://qiakr.kf5.com/attachments/download/114281/00155752eb98454c21ea2f813e28419/" title="" alt="blob.png"></p><p><br></p><p>选择“创建专题页面”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/114286/00155752f16d33ad5f7656f8f9077bb/" title="" alt="blob.png"><br></p><p><br></p><p>选择主题类型、活动主图、专题名称、专题描述、列表标题等信息。</p><p>这些信息编辑时，左侧的手机界面都会有实时的预览效果，您可以查看效果。</p><p><br></p><p>点击“下一步”继续完成商品专题的商品信息。</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/114300/00155752fbd76e2ed326ebe09e85e5a/" title="" alt="blob.png"><br></p><p><br></p><p>点击“添加商品”</p><p><img src="https://qiakr.kf5.com/attachments/download/114304/001557530072108d173ccab955d3f49/" title="" alt="blob.png"></p><p><br></p><p>通过上方关键词搜索找到需添加的商品，选择左侧的勾选框选中商品，选中后点击“确定”即可完成商品添加。</p><p><img src="https://qiakr.kf5.com/attachments/download/114316/001557530f9d8e534a7b7d1be81e638/" title="" alt="blob.png"></p><p><br></p><p>可以继续编辑商品的卖点信息，如左侧手机预览，卖点信息会在商品标题下方显示。</p><p><br></p><p>所有操作完成后，即可点击“保存页面”创建商品专题。</p><p><img src="https://qiakr.kf5.com/attachments/download/114330/00155753235ab27bf9783bb7d5ed8dd/" title="" alt="blob.png"></p><p><br></p><p>回到专题列表页后，可以点击对应专题的“复制链接”选项，复制当前专题的链接。</p><p><br></p><p>您可以将专题链接通过微信公众号群发推送，也可以将链接设置为微信公众号的自定义菜单。</p></div>'
	},
	{
		id:19,
		name:"抢红包活动设置",
		content:"设置红包让用户随机领取优惠券，吸引用户参与并分享到朋友圈扩散",
		video:"https://qncdn.qiakr.com/movie/抢红包活动设置",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2"><li><p>每天可自主设置红包让用户随机领取，红包内可以塞入3种类型优惠券，吸引用户参与同时也引导用户分享到朋友圈扩散活动。</p></li><li><p><a href="https://qiakr.kf5.com/posts/view/39418/" target="blank">使用场景：抢红包</a></p></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113432/001557421530df63a934fd3d27b2f60/" title="" alt="blob.png"><br></p><p><br></p><p>进入后台活动板块，选择“抢红包”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113434/0015574221779bbed8c172ffae076d5/" title="" alt="blob.png"></p><p><br></p><p><br></p><p>选择“添加红包”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113435/0015574229434ec5c90dc9d45d3579f/" title="" alt="blob.png"><br></p><p><br></p><p>一个红包最多可塞入三种类型的优惠券，进入后默认会让您选择第一中优惠券。</p><p><br></p><blockquote><p>输入优惠券名称、优惠券有效期等基础信息。</p><p>优惠券名称：会在会员的优惠券信息里显示，比如“五一特惠券”等</p><p>优惠券有效期：会员若领取到该优惠券，只能在这段时间里使用。</p><p>商品限制：若该券只针对特定商品才可使用，选择后选择特定商品即可。</p><p>品类限制：若该券只针对特定品类才可使用，选择后选择特定品类即可。</p><p>优惠券信息编辑无误后，点击“确定”</p></blockquote><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113436/0015574245c01a06b2e7be550701b33/" title="" alt="blob.png"></p><p><br></p><p>可以继续点击“添加优惠券”按钮为红包添加最多三种类型优惠券。</p><p><span style="color:rgb(255,0,0);"><strong>最大面值的红包会在微信领红包界面显示，所以建议您至少设置一个大面额红包激励用户。</strong></span></p><p><br></p><blockquote><p>发放数量：该优惠券一共可以发出几张（被会员领到）</p><p>中奖概率：最大概率（人人有奖）、一般概率（有几率中奖）、最小概率（很难中奖）三种可选择，可根据券的数量和价值进行选择。</p><p>红包发放时间：红包在这个时间段内才可被用户领取，不在时间段则无法领取。</p><p><span style="color:rgb(255,0,0);">红包发放时间不可与已存在的红包重复，目前抢红包是一个固定的活动页面，所以每个时间段的红包不能重复。</span></p></blockquote><p><br></p><p>最后点击“确认”即可完成该红包的创建。</p><p><br></p><p>完成后可以点击 &nbsp;<a href="https://qiakr.kf5.com/posts/view/39418/" target="blank">使用场景：抢红包</a>&nbsp; 查看红包使用场景，点击 &nbsp;<a href="https://qiakr.kf5.com/posts/view/39901/" target="blank">如何推广红包</a>&nbsp; 查看红包活动如何扩散，点击 <a href="https://qiakr.kf5.com/posts/view/39902/" target="blank">如何提高优惠券使用率</a>&nbsp;查看红包使用率提高技巧，</p><p><br></p><p><br></p></div>'
	},
	{
		id:20,
		name:"天天闪购活动设置",
		content:"设置秒杀活动，活跃老会员并引客到店，秒杀商品在线支付后，可前往门店自提",
		video:"https://qncdn.qiakr.com/movie/天天闪购活动设置",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2"><li><p>可通过时间段设置秒杀活动，活跃老会员，秒杀商品在线支付后，可前往门店自提。</p></li><li><p><a href="https://qiakr.kf5.com/posts/view/39416/" target="blank">使用场景：天天闪购</a><br><br></p><p><a href="https://qiakr.kf5.com/posts/view/39416/" target="blank"></a></p></li></ul><p><img src="https://qiakr.kf5.com/attachments/download/113447/00155742a9b94ea86fa88dbd9417484/" title="" alt="blob.png"><br></p><p><br></p><p>进入后台活动板块，选择“天天闪购”</p><p><br></p><p><strong>一. 添加闪购商品</strong></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113894/0015574fdfbb131812bee11500a98e9/" title="" alt="blob.png"><br></p><p><br></p><p>点击“添加商品”，创建您的首个闪购活动商品。闪购商品会从总库商品中选择，请先确保商品已经在总库内录入。</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113903/0015574fee89bd463a651d57064b0d3/" title="" alt="blob.png"></p><p><br></p><p>选择闪购商品，左侧勾选后，点击保存。</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113939/001557501a8d4e0a1a03f426c7334a5/" title="" alt="blob.png"><br></p><p><br></p><p>设置闪购活动时间、闪购价格</p><p>闪购活动时间：会员再此时间段内才可参与闪购活动进行秒杀。</p><p>闪购价格：活动时间内的闪购实际售价。</p><p>闪购数量：实际闪购的数量，请注意备货情况。（该闪购数量将不受原商品库存影响，该数量为独立库存数量）</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113951/001557502c3743610175677c9d4c423/" title="" alt="blob.png"><br></p><p><br></p><p><strong>物流方式：</strong>默认为仅限到店自提，会员在微信里下单后需要前往对应的自提门店自提；您可以选择“到店自提及快递送货”，这样会员下单的时候可以在快递发货和到店自提里做选择。</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113979/001557506b98b2ec89478b5b95a646a/" title="" alt="blob.png"><br></p><p>点击“选择自提门店”</p><p><strong>自提门店：</strong>用户在微信下单时，若选择门店自提，需要在这些门店内做选择。看您商品库存的门店分布情况，可以将库存充分分配到几个门店，避免会员自提时门店无货的情况。</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113981/001557507753db0b15f9c463d301fdb/" title="" alt="blob.png"><br></p><p><br></p><p>最后点击“确认”即可完成闪购商品的创建。</p><p><br></p><p><strong><span style="color:rgb(255,0,0);">闪购商品特别说明：</span></strong></p><p><span style="color:rgb(255,0,0);">a. 闪购商品设置后，原始的总库商品仍将按原始价格出售，价格和库存均不受影响；需通过闪购活动页面进入才可参与该商品的闪购。</span></p><p><span style="color:rgb(255,0,0);">b. 闪购商品设置后，为独立商品，原始总库商品下架删除都不会影响到闪购商品，若要中途停止闪购活动，见下方停止活动说明。</span></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113991/0015575092343f1d88e47d00415308a/" title="" alt="blob.png"><br></p><p><br></p><p>这时候就可以在闪购活动的列表，看到即将开始或已经开始的闪购商品列表。</p><p><br></p><p>如果设置有误，可以点击“取消活动”把活动暂停，但若该活动已开始并产生了订单，临时取消活动，历史订单无法取消。</p><p><br></p><p><strong>二. 闪购活动页面修改</strong></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/113889/0015574fd9590e86db51bcf5aa0afc2/" title="" alt="blob.png"></p><p><br></p><p>点击上方的“闪购基本信息”，可查看闪购活动图片和文案设置，可自行进行修改并保存。</p><p><br></p><p>完成后可以点击 <a href="https://qiakr.kf5.com/posts/view/39416/" target="blank">使用场景：天天闪购</a><a href="https://qiakr.kf5.com/posts/view/39418/" target="blank"></a>&nbsp; 查看天天闪购使用场景，点击 &nbsp;<a href="https://qiakr.kf5.com/posts/view/39904/" target="blank">如何推广闪购活动</a>&nbsp; 查看红包活动如何扩散。</p></div>'
	},
	{
		id:21,
		name:"优惠券核销",
		content:"",
		video:"https://qncdn.qiakr.com/movie/%E4%BC%98%E6%83%A0%E5%88%B8%E6%A0%B8%E9%94%80",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><h2><strong>消费者优惠券查找</strong></h2></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/270487/001561dde5e1572e61048e78c5aba3b/" title="" alt="blob.png" width="611" height="470" style="width:611px;height:470px;"></p><p>进入商家店铺，点击右上角图标进入个人中心界面</p><p>在个人中心界面点击“我的优惠券”进入优惠券列表页面</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/270492/001561de06ccaedd9bb6e6f6617cfc9/" title="" alt="blob.png" width="605" height="426" style="width:605px;height:426px;"></p><p>选中想要使用的优惠券，并点击进入即可查看优惠券使用期限、优惠券码等信息</p><p>消费者将优惠券码或该页面出示给导购即可完成优惠券核销</p><p><br></p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><h2><strong>导购端优惠券核销</strong></h2><p><br></p></li></ul><p><img src="https://qiakr.kf5.com/attachments/download/270557/001561deaf331c4ad738deef1d8cb9b/" title="" alt="blob.png" width="756" height="384" style="width:756px;height:384px;"></p><p>进入导购端个人中心，点击“卡券核销”打开核销功能（请先PC商家管理后台开通导购核销权限设置）</p><p>手动输入消费者提供的卡券码，或者通过扫一扫获取，确认后点击“下一步”</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/270577/001561dedd3d3ee2b3ddd6811611faa/" title="" alt="blob.png" width="609" height="475" style="width:609px;height:475px;"></p><p>进入核销环节，按照界面提示依次填写各项信息</p><blockquote><ul class="list-paddingleft-2" style="list-style-type:circle;"><li><p>订单金额（必填）</p></li></ul><p>使用优惠券前的支付金额</p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:circle;"><li><p>支付方式（必选）</p></li></ul><p>现金支付：消费者使用现金或者POS机刷卡支付</p><p>微信支付：消费者使用微信钱包支付</p><p>支付宝支付：消费者使用微信钱包支付</p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:circle;"><li><p>订单商品（选填）</p></li></ul><p>记录消费者购买商品，利于商家跟踪记录消费者行为习惯，建议添加</p></blockquote><p>全部添加完成后点击“确认核销”进入支付环节</p><p><br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/270604/001561df199f1da1b6e7863e80b48e5/" title="" alt="blob.png" width="609" height="463" style="width:609px;height:463px;"></p><p>进入支付环节后，系统会自动计算出使用优惠券后的金额，然后依据页面提示进行支付</p><p><br></p><p><span style="color:rgb(127,127,127);">*使用现金支付务必在线下实际收到款项后再点击“确认收到现金”</span></p><p><br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/270629/001561df41d34593fbf47d28b436312/" title="" alt="blob.png" width="607" height="462" style="width:607px;height:462px;"></p><p>卡券核销成功后会收到系统提示</p><p>点击“查看核销详情”可进入订单界面查看详情</p></div>'
	},
	{
		id:22,
		name:"管理后台子账号&权限设置",
		content:"给需要使用商家管理后台的员工添加子账号，并通过设置角色来管理权限",
		video:"https://qncdn.qiakr.com/%E7%AE%A1%E7%90%86%E5%90%8E%E5%8F%B0%E5%AD%90%E8%B4%A6%E5%8F%B7&%E6%9D%83%E9%99%90%E8%AE%BE%E7%BD%AE",
		imgText:'<div class="original-content"><p><strong>该功能板块可设置管理员、商品管理员、订单管理员等多个角色账号，并支持自定义账号角色操作权限。&nbsp;解决多人共享一个账号问题，提高后台安全性：</strong></p><p><strong>a.&nbsp;老板注册账号后，可设置员工为管理员负责相关后台执行工作。<br>b. 商品编辑人员、订单发货人员、活动管理人员单独配置商品、订单、活动权限。<br>c. 后台管理员离职后，可自主删除管理员账号。</strong></p><p><br></p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><p>角色权限设置</p></li></ul><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/310472/0015643168409de2caf11666edab356/" title="" alt="blob.png" width="1" height="1" style="width:1px;height:1px;"><img src="https://qiakr.kf5.com/attachments/download/310546/00156432381cd2ed41f0643889ae347/" title="" alt="blob.png" width="736" height="363" style="width:736px;height:363px;"></p><p>进入PC端商家管理后台首页，从界面右上角【设置】进入【权限设置】，然后在左侧导航栏点击【管理后台权限】进入权限设置界面，在界面中点击【角色管理】进入</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/310520/00156431e84311607349f360ca1f779/" title="" alt="blob.png" width="717" height="283" style="width:717px;height:283px;"></p><p>列表中为系统默认的角色设置，商户可以点击右上角【添加角色】添加新的角色</p><blockquote><p>后台管理员：可以进行除了“管理后台角色权限”设置的所有操作。建议为项目负责人或者区经/督导以上级别人员</p><p>商品管理员：对总库、门店自建以及微商城进行商品管理，建议为总部负责相关业务的专员</p><p>数据分析员：查看全门店数据。建议为总部负责相关业务的专员</p><p>活动管理员：新会员送券、买后送券等营销活动设置。建议为总部负责相关业务的专员</p><p>订单管理员：管理订单发货、订单导出、运费设置等订单相关操作。建议为总部负责相关业务的专员</p><p>超级管理员：所有操作权限（包括删除后台管理员），为商户注册绑定手机号用户，有且只有一个</p></blockquote><p>或者点击角色栏右侧的【编辑权限】对单个角色的权限经行编辑</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/310539/0015643226abc130f4cea7e3c3ca663/" title="" alt="blob.png"></p><p><br></p><p>根据您需要对不同角色设置的功能开启/关闭相应权限，完成后保存设置<br></p><p><br></p><p><br></p><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><p>添加子账号</p></li></ul><p><br></p></div>'
	},
	{
		id:23,
		name:"满减满折活动设置",
		content:"设置满减满折活动，提升进店转化率和连带率",
		video:"https://qncdn.qiakr.com/%E6%BB%A1%E5%87%8F%E6%BB%A1%E6%8A%98%E6%B4%BB%E5%8A%A8%E8%AE%BE%E7%BD%AE",
		imgText:'<div class="original-content"><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/312518/001564459f2766858c8839267e8a07f/" title="" alt="blob.png"></p><p>进入商家管理后台，点击【活动】-【满减满折】进入活动设置界面</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/312664/001564463cf448c9e1717ad5ca701a9/" title="" alt="blob.png"></p><p>点击【进行中】【未开始】【已结束】标签可以分别查看相应状态下的活动列表和相关信息</p><p>如果要创建新活动点击右上方【创建满减优惠】</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/312690/0015644651229d201616fbfa5ed8ac0/" title="" alt="blob.png"></p><p>根据系统提示填写相应活动信息</p><p>完成后点击【保存】即可<br></p><p><br></p><p><strong>满减优惠活动说明</strong></p><p>1. 活动参与商品可根据单品、品牌、品类或全部商品；活动参与门店可选择全店或部分门店参与。</p><p>2. 优惠内容可根据需求选择满金额减或满件折扣；满件折扣的计算方法，满足条件后所有商品根据折扣进行计算。</p><p>示例，商品A售价100元、商品B售价200元，商品C售价300，满足2件8折；则订单内商品A成交价为80元、商品B成交价为160元，商品C成交价为240元</p><p>3. 若订单内包含多个商品，部分商品满足满减优惠，则部分商品实际成交价根据规则调整，其它商品仍然按照售价。</p><p>示例，商品A售价100元、商品B售价200元、商品C售价300元，A和B满足2件8折（商品C不在活动内）；则订单内商品A成交价为80元、商品B成交价为160元、商品C成交价为300元。</p><p>4. 若设置了多个满减优惠活动，购物车内商品均满足活动要求，下单时消费者只可选择一个优惠活动（默认会选择优惠最多的方式）</p><p>5. 优惠券与满减优惠为平级优惠，消费者若选择满减优惠则无法使用优惠券（消费者可手动选择不参与减免活动，则可选择优惠券）</p><p><br></p><p><br></p></div>'
	},{
		id:24,
		name:"导购二维码邀请会员（加粉）",
		content:"使用APP上的邀请会员功能，使消费者成为您公众号的粉丝",
		video:"https://qncdn.qiakr.com/movie/0080003.mp4?v=1",
		imgText:'<div class="original-content"><ul class="list-paddingleft-2" style="list-style-type:disc;"><li><p><span style="color:rgb(255,0,0);"><strong>该功能可以使客户快速添加导购并同时关注商家服务号，建立与导购/商家之间的沟通渠道</strong></span></p></li><li><p><span style="color:rgb(255,0,0);"><strong>使用标签功能能够帮助导购、商家记录客户的个人喜好、使用习惯等信息，达成精准营销</strong></span></p></li></ul><p><br></p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/392740/001567a522d3a418e6c07a5b3ae428f/" title="" alt="blob.png" width="367" height="587" style="width:367px;height:587px;"></p><p></p><p>打开导购端，点击右下角“我的”进入个人中心界面</p><p>点击主功能区“邀请会员”即可进入二维码生成界面</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/392755/001567a5380c5db5308a549ddb2c918/" title="" alt="blob.png" width="368" height="585" style="width:368px;height:585px;"></p><p>让客户使用微信“扫一扫”功能扫描导购二维码添加其为专属导购<br></p><blockquote><p>客户扫描二维码后会进入商家服务号，点击关注后即可添加导购并同时关注商家服务号</p></blockquote><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/172476/00155b6f5db6fc6d5b2759b978a9715/" title="" alt="blob.png" width="297" height="493" style="width:297px;height:493px;"><img src="https://qiakr.kf5.com/attachments/download/172482/00155b6f63fe3e3b14a5a1d37a7627d/" title="" alt="blob.png" width="298" height="489" style="width:298px;height:489px;"></p><p>点击下方菜单栏中的“客户”进入客户列表，客户列表中默认第1位就是刚添加的会员（如果不是，可以点击右上角图标，通过将排序方式更改为“按加入时间排序”找到最新添加的客户），点击会员头像即可查看会员信息</p><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/172542/00155b6fff457dba33af9f815e12f81/" title="" alt="blob.png" width="343" height="596" style="width:343px;height:596px;"></p><p><br></p><blockquote><p>点击右上角“…”按钮打开更多，即可编辑为会员添加自定义备注/标签</p><p>点击底部“发消息”即可与客户通过商户服务号沟通</p><p>点击底部“拨打电话”即可直接拨打客户电话</p></blockquote><p><br></p><p><img src="https://qiakr.kf5.com/attachments/download/172798/00155b727e0ef84fdace03318285202/" title="" alt="blob.png" width="577" height="433" style="width:577px;height:433px;"></p><p>*&nbsp;以上分别为消费者端和导购端对话效果预览图</p></div>'
	}
];

var id = Util.getUrlParam("id");
if(task[id]){
	template.config('escape', false)
	var dataHtml = template('tempData', task[id]);
	$("#courseContent").html(dataHtml);
}